### ISSUE TITLE
Fail to build with Qt6.5.3

### ISSUE THREAD

**Issue by FinitelyFailed** [maplibre/maplibre-native-qt#52]
**Describe the bug**
I'm trying to build with Qt6.5.3 on Ubuntu.

**To Reproduce**
1. clone repo
2. git submodule update --init --recursive
3. mkdir build && cd build
4. ~/Qt6/6.5.3/gcc_64/bin/qt-cmake .. -B . -GNinja
5. ninja
6. Error:
```
[391/413] Linking CXX executable test/core/test_mln_core
FAILED: test/core/test_mln_core 
: && /usr/bin/c++   test/core/CMakeFiles/test_mln_core.dir/test_mln_core_autogen/mocs_compilation.cpp.o test/core/CMakeFiles/test_mln_core.dir/__/common/test_rendering.cpp.o test/core/CMakeFiles/test_mln_core.dir/map_tester.cpp.o test/core/CMakeFiles/test_mln_core.dir/test_core.cpp.o -o test/core/test_mln_core  -Wl,-rpath,/home/tmm/Documents/dev/qt/maplibre-native-qt/build/src/core:/home/tmm/Qt6/6.5.3/gcc_64/lib  src/core/libQMapLibre.so.3.0.0  /home/tmm/Qt6/6.5.3/gcc_64/lib/libQt6OpenGLWidgets.so.6.5.3  /home/tmm/Qt6/6.5.3/gcc_64/lib/libQt6OpenGL.so.6.5.3  /home/tmm/Qt6/6.5.3/gcc_64/lib/libQt6Widgets.so.6.5.3  /home/tmm/Qt6/6.5.3/gcc_64/lib/libQt6Test.so.6.5.3  /home/tmm/Qt6/6.5.3/gcc_64/lib/libQt6Gui.so.6.5.3  /usr/lib/x86_64-linux-gnu/libGLX.so  /usr/lib/x86_64-linux-gnu/libOpenGL.so  /home/tmm/Qt6/6.5.3/gcc_64/lib/libQt6Network.so.6.5.3  /home/tmm/Qt6/6.5.3/gcc_64/lib/libQt6Sql.so.6.5.3  /home/tmm/Qt6/6.5.3/gcc_64/lib/libQt6Core.so.6.5.3 && :
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `u_shapeArabic_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_writeReordered_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_open_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_setPara_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_getProcessedLength_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `u_errorName_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_countRuns_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_getParagraphByIndex_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_close_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_countParagraphs_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_setLine_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_writeReverse_70'
/usr/bin/ld: src/core/libQMapLibre.so.3.0.0: undefined reference to `ubidi_getVisualRun_70'
collect2: error: ld returned 1 exit status
[396/413] Building CXX object src/location/CMakeFiles/Location.dir/qgeomap.cpp.o
ninja: build stopped: subcommand failed.
```

**Expected behavior**
A successful build

**Platform information (please complete the following information):**
 - OS: Kubuntu 22.04
 - Qt version Qt 6.5.3

**Additional context**
Do this have something to do with this issue: [https://github.com/maplibre/maplibre-native-qt/issues/39](https://github.com/maplibre/maplibre-native-qt/issues/39)

**Comment by emericg** [comment]
You can use the build settings from this page : https://github.com/maplibre/maplibre-native/blob/main/platform/qt/README.md
the important one for your issue being `-DMLN_WITH_QT=ON`

**Comment by FinitelyFailed** [comment]
> You can use the build settings from this page : https://github.com/maplibre/maplibre-native/blob/main/platform/qt/README.md the important one for your issue being `-DMLN_WITH_QT=ON`

Thanks for your reply. However that gave me the same error as before. I removed the build dir and started from scratch but got the same error.

I tried with `-DMLN_QT_WITH_INTERNAL_ICU=ON` tho which made it build.

**Comment by ntadej** [comment]
Yes, there are issues with ICU, I opened #39. It seems that there's an interference between internal one and system one. I'll try to have a look as soon as possible.

**Comment by ntadej** [comment]
ICU handling has been improved with #56, closing.
